function(LIST_PREFIX source_list prefix)
  set(_tmp_list)
  foreach(_list_item ${ARGN})
    list(APPEND _tmp_list "${prefix}/${_list_item}")
  endforeach()
  set(${source_list} "${_tmp_list}" PARENT_SCOPE)
endfunction()

function(CHECK_ALL_EXISTS out_var)
  set(_result TRUE)
  foreach(_list_item ${ARGN})
    if(EXISTS "${_list_item}")
    else()
      message(STATUS "File or directory ${_list_item} does not exists!")
      set(_result FALSE)
      break()
    endif()
  endforeach()
  set(${out_var} ${_result} PARENT_SCOPE)
endfunction()
